// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace CreateNewDatabaseAoo.Models;

/// <summary>
/// For EF Core work
/// </summary>
public partial class Person
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? Pin { get; set; }
    public DateOnly BirthDate { get; set; }
}