// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace SampleApp2.Models;

public partial class ContactType : INotifyPropertyChanged
{
    private string _contactTitle;
    public int ContactTypeIdentifier { get; set; }

    public string ContactTitle
    {
        get => _contactTitle;
        set
        {
            if (value == _contactTitle) return;
            _contactTitle = value;
            OnPropertyChanged();
        }
    }

    public virtual ICollection<Contacts> Contacts { get; set; } = new List<Contacts>();
    public override string ToString() => ContactTitle;

    public event PropertyChangedEventHandler PropertyChanged;

    protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}